// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-zWtjst_Qq1XrsPkQ4HH4eBJ1jFXboA',
    appId: '1:464992689824:web:40f4c2cbdee87898eab3c5',
    messagingSenderId: '464992689824',
    projectId: 'slicing-task',
    authDomain: 'slicing-task.firebaseapp.com',
    storageBucket: 'slicing-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKaelFL_aQKHFc611s6odSio5YbXyIJWg',
    appId: '1:464992689824:android:f2e8f7be890c7df3eab3c5',
    messagingSenderId: '464992689824',
    projectId: 'slicing-task',
    storageBucket: 'slicing-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJ4TV3VAhIZTIs_hLFWYwtP61YZiiulI',
    appId: '1:464992689824:ios:242f163a1693bd7aeab3c5',
    messagingSenderId: '464992689824',
    projectId: 'slicing-task',
    storageBucket: 'slicing-task.firebasestorage.app',
    iosBundleId: 'com.gamingfo.gamingfoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJ4TV3VAhIZTIs_hLFWYwtP61YZiiulI',
    appId: '1:464992689824:ios:242f163a1693bd7aeab3c5',
    messagingSenderId: '464992689824',
    projectId: 'slicing-task',
    storageBucket: 'slicing-task.firebasestorage.app',
    iosBundleId: 'com.gamingfo.gamingfoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq-zWtjst_Qq1XrsPkQ4HH4eBJ1jFXboA',
    appId: '1:464992689824:web:b1d7693ecb5d571aeab3c5',
    messagingSenderId: '464992689824',
    projectId: 'slicing-task',
    authDomain: 'slicing-task.firebaseapp.com',
    storageBucket: 'slicing-task.firebasestorage.app',
  );
}
